// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-my-restaurants.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_restaurants_default = defineTool({
  name: "list_my_restaurants",
  title: "Listar meus restaurantes",
  description: "Lista os restaurantes que pertencem ao usu\xE1rio autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("restaurants").select("id,name,slug,whatsapp,is_open,is_blocked,delivery_enabled,pickup_enabled,created_at").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { restaurants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_orders_default = defineTool2({
  name: "list_orders",
  title: "Listar pedidos",
  description: "Lista os pedidos mais recentes de um restaurante do usu\xE1rio. Filtra opcionalmente por status.",
  inputSchema: {
    restaurantId: z.string().uuid().describe("ID do restaurante"),
    status: z.enum(["pending", "preparing", "delivering", "completed", "delivered", "cancelled"]).optional().describe("Filtrar por status do pedido"),
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de pedidos (padr\xE3o 50)")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ restaurantId, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("orders").select(
      "id,order_number,customer_name,customer_phone,status,payment_status,payment_method,subtotal,delivery_fee,total,created_at"
    ).eq("restaurant_id", restaurantId).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_products_default = defineTool3({
  name: "list_products",
  title: "Listar produtos do card\xE1pio",
  description: "Lista os produtos do card\xE1pio de um restaurante do usu\xE1rio.",
  inputSchema: {
    restaurantId: z2.string().uuid().describe("ID do restaurante"),
    onlyActive: z2.boolean().optional().describe("Retornar apenas produtos ativos")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ restaurantId, onlyActive }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser3(ctx).from("products").select("id,name,description,price,category_id,is_active,is_featured,image_url,display_order").eq("restaurant_id", restaurantId).order("display_order", { ascending: true });
    if (onlyActive) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/sales-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var sales_summary_default = defineTool4({
  name: "sales_summary",
  title: "Resumo de vendas",
  description: "Retorna quantidade de pedidos e faturamento de um restaurante em um per\xEDodo (pedidos cancelados s\xE3o exclu\xEDdos).",
  inputSchema: {
    restaurantId: z3.string().uuid().describe("ID do restaurante"),
    days: z3.number().int().min(1).max(90).optional().describe("\xDAltimos N dias (padr\xE3o 30)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ restaurantId, days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const window = days ?? 30;
    const since = new Date(Date.now() - window * 24 * 60 * 60 * 1e3).toISOString();
    const { data, error } = await supabaseForUser4(ctx).from("orders").select("total,status,created_at").eq("restaurant_id", restaurantId).gte("created_at", since);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const valid = (data ?? []).filter((o) => o.status !== "cancelled");
    const revenue = valid.reduce((sum, o) => sum + Number(o.total || 0), 0);
    const summary = {
      periodDays: window,
      totalOrders: valid.length,
      cancelledOrders: (data ?? []).length - valid.length,
      revenue: Number(revenue.toFixed(2)),
      averageTicket: valid.length ? Number((revenue / valid.length).toFixed(2)) : 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "defowjmlqmheecydnyrj";
var mcp_default = defineMcp({
  name: "clica-e-pede-mcp",
  title: "Clica e Pede",
  version: "0.1.0",
  instructions: "Ferramentas para consultar restaurantes, card\xE1pio, pedidos e resumo de vendas do usu\xE1rio autenticado no Clica e Pede. Todas as tools respeitam RLS: cada usu\xE1rio s\xF3 enxerga seus pr\xF3prios dados.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_restaurants_default, list_orders_default, list_products_default, sales_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
